name: Actions Workflow
on:
  push:
    branches:
      - 'release/v[0-9]+.[0-9]+'
  pull_request:
    branches:
      - 'release/v[0-9]+.[0-9]+'
jobs:
  actions_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Standardize
        run: echo "Running standardization script"
